spring:
  application:
    name: agenda-docker
  profiles:
    active: local

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5434/database
#    driver-class-name: org.postgresql.Driver
#    username: username
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true